name: CI

on: push

env:
  BUN_VERSION: '1.0.2'

jobs:
  build:
    name: Build ğŸ—ï¸
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Bun âš™ï¸
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Install dependencies ğŸ”§
        run: bun i

      - name: Build ğŸ—ï¸
        run: bun run build

  lint:
    name: Lint âœ…
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Bun âš™ï¸
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Install dependencies ğŸ”§
        run: bun i

      - name: Lint âœ…
        run: bun run lint

  tsc:
    name: TypeScript Compiler ğŸ”
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Bun âš™ï¸
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Install dependencies ğŸ”§
        run: bun i

      - name: TypeScript Compiler ğŸ”
        run: bun run tsc

  test:
    name: Test ğŸ§ª
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Bun âš™ï¸
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Install dependencies ğŸ”§
        run: bun i

      - name: Test ğŸ§ª
        run: bun run test-coverage

  npm-release:
    name: npm release ğŸ“¦
    needs: [build, lint, tsc, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Bun âš™ï¸
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Install dependencies ğŸ”§
        run: bun i

      - name: Build ğŸ—ï¸
        run: bun run build

      - name: Release ğŸš€
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun run semantic-release
